import java.util.List;

public class NodeNames {

    public static List<String> NAMES = List.of(
            "ABDULRAZAGH I ZMIRLI",
            "Acquarius Management Services Limited",
            "Adel M. Moh Abufliga",
            "ALEXANDER GOLBRAIKH",
            "ALFREDO SPITERI DEBARRO",
            "ANDREW GRECH",
            "ANTHONY AQUILINA",
            "ANTHONY BRIFFA",
            "ANTHONY FENECH",
            "ANTOINE MEYNIAL",
            "AREF ALTAWAM",
            "ASTOR LANE S.A.",
            "AUDINA MANAGEMENT SERVICES LTD.",
            "BERNARD DARMANIN",
            "BERNARD ZAMMIT",
            "BERNICE CAMILLERI",
            "CA HOLDINGS LIMITED",
            "CARIDAD TEODORA MENDOZA GONZALEZ",
            "CAROLINE LABEILLE",
            "C.C.S. DIRECTORS LIMITED",
            "CHAN - Bessie Pui Shan",
            "Chancel - Eva",
            "Chan - Chart Man",
            "CHAN - Chee Keong",
            "CHAN - Cher Boon",
            "CHAN - Chi Chung",
            "CHAN - Chi Yuen",
            "Chandler Jr - Richard Edwin",
            "Chandra - Subhash",
            "CHAN - Ella Pui Man",
            "CHAN - George Ching Cheong",
            "Chang - In Soo",
            "Chang - Kuo-Cheng",
            "Chang - Mike F.",
            "CHRIS BONETT",
            "CHRISTOPHER AQUILINA",
            "CHRISTOPHER BORG",
            "CHRISTOPHER CACHIA",
            "CHRISTOPHER KAYE",
            "CHRISTOPHE ROGER BLIN",
            "CLARISSA PACE",
            "CLAYTON FENECH",
            "CYRIL JEAN ANDRE DELAMARE",
            "DANIEL CAMILLERI",
            "DAVID AKA STEPHEN GANADO",
            "DAVID CANALS IMOHR",
            "DAVID CASHA",
            "DAVID ISAAC",
            "DELTA INTERNATIONAL FOUNDATION",
            "DEREK CONTI",
            "DIANE MAGRO DELIA",
            "Dogan Erbek",
            "DOMINIC SAYWELL",
            "DOMLIAR LIMITED",
            "DUNCAN AGIUS",
            "DUNCAN MICALLEF",
            "Elpida  Agapiou",
            "EL PORTADOR",
            "Emad Ayad Dowas",
            "EPA TUIOTI",
            "Euro-Amex Exchange, Inc.",
            "FIDEHOLD MANAGEMENT LTD.",
            "FINSTOCK HOLDING SA",
            "FORMIA LIMITED",
            "Francesca Bianchi",
            "FRANCO VELLA",
            "FRANKEN, GLENDA ARLINDA",
            "Franklin Alexis San Martin Gonzalez",
            "GAIRNS LTD.",
            "GEORGE HILL NOMINEES LIMITED",
            "GEORGE RICHARD MARSHALL PURCHASE",
            "GISELLE CAMILLERI",
            "GUIDO ENGEL",
            "HABIBE- VROLIJK, DIANNE ARLENE",
            "HANNES BAUMGARTNER",
            "HARPO S.A.",
            "HARRISON WENDY PATRICIA",
            "HENRIQUEZ, OSYTH ALISTAIRE",
            "HOLFORD ROGER",
            "H T C ADMINISTRATION & TRUST N.V.",
            "HUGO CHETCUTI",
            "IBRAHIM ALI ABULOHOUM",
            "INTERCON LIMITED",
            "IVAN VELLA",
            "JAKOV KARMELIC",
            "JAMES CUSCHIERI",
            "JAMES JOHN HARDIE LOCKHART",
            "JAN TORSTEN SUNDGREN",
            "JEAN PAUL SPITERI",
            "JENNIFER BENITO PASCUAL",
            "Jennifer Piccinino",
            "JOHN SULLIVAN",
            "JONATHAN SCIFO DIAMANTINO",
            "JOSEPHINE ABELA",
            "JOSEPHINE BORG",
            "JOSEPH MICHAEL COHEN",
            "JOSEPH QUATTROMANI",
            "KARL ERIK PETER WAHLBERG",
            "KENNETH J DIMECH",
            "KEVIN BRETT DEAN"
    );
}
