version: '3'
services:
  neo4j:
    image: neo4j:3.5
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - EXTENSION_SCRIPT=/neo4j-init/init.sh
      - NEO4J_AUTH=none
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4JLABS_PLUGINS=["apoc"]
    volumes:
      - ./neo4j-init:/neo4j-init
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres/import-panama.sql:/docker-entrypoint-initdb.d/import-panama.sql
      - ./neo4j-init/panama.csv:/panama.csv
