version: '3'
services:
  neo4j:
    image: neo4j:3.5
    ports:
     - "7474:7474"
     - "7687:7687"
    environment:
     - EXTENSION_SCRIPT=/neo4j-init/init.sh
     - NEO4J_AUTH=none
    volumes:
     - ./neo4j-init:/neo4j-init
