CREATE TABLE offshoreleaks_import
(
    _id                      varchar,
    _labels                  varchar,
    address                  varchar,
    addressID                varchar,
    closed_date              varchar,
    comments                 varchar,
    company_number           varchar,
    company_type             varchar,
    countries                varchar,
    country                  varchar,
    country_code             varchar,
    country_codes            varchar,
    dorm_date                varchar,
    end_date                 varchar,
    entity_number            varchar,
    former_name              varchar,
    ibcRUC                   varchar,
    icij_id                  varchar,
    inactivation_date        varchar,
    incorporation_date       varchar,
    internal_id              varchar,
    jurisdiction             varchar,
    jurisdiction_description varchar,
    lastEditTimestamp        varchar,
    name                     varchar,
    node_id                  varchar,
    note                     varchar,
    original_address         varchar,
    original_name            varchar,
    registered_office        varchar,
    registration_date        varchar,
    service_provider         varchar,
    sourceID                 varchar,
    status                   varchar,
    struck_off_date          varchar,
    tax_stat_description     varchar,
    type                     varchar,
    valid_until              varchar,
    edge_start               varchar,
    edge_end                 varchar,
    edge_type                varchar,
    edge_end_date            varchar,
    edge_lastEditTimestamp   varchar,
    edge_link                varchar,
    edge_sourceID            varchar,
    edge_start_date          varchar,
    edge_status              varchar,
    edge_valid_until         varchar
);

COPY offshoreleaks_import (
                    _id,
                    _labels,
                    address,
                    addressID,
                    closed_date,
                    comments,
                    company_number,
                    company_type,
                    countries,
                    country,
                    country_code,
                    country_codes,
                    dorm_date,
                    end_date,
                    entity_number,
                    former_name,
                    ibcRUC,
                    icij_id,
                    inactivation_date,
                    incorporation_date,
                    internal_id,
                    jurisdiction,
                    jurisdiction_description,
                    lastEditTimestamp,
                    name,
                    node_id,
                    note,
                    original_address,
                    original_name,
                    registered_office,
                    registration_date,
                    service_provider,
                    sourceID,
                    status,
                    struck_off_date,
                    tax_stat_description,
                    type,
                    valid_until,
                    edge_start,
                    edge_end,
                    edge_type,
                    edge_end_date,
                    edge_lastEditTimestamp,
                    edge_link,
                    edge_sourceID,
                    edge_start_date,
                    edge_status,
                    edge_valid_until
    )
    FROM '/panama.csv'
    DELIMITER ','
    CSV HEADER;
